POST http://127.0.0.1:8000/api/v1/users/create_user
Content-Type: application/json


{
  "email": "Coach1@example.com",
  "password": "securepassword",
  "role": "Coach",
  "username": "Coach1",
  "belt": "Black",
  "coach_bio": "I am  a coach",
  "price": 69,
  "height": 175,
  "weight": 200,
  "expertise": ["everything", "im", "awesome"],
  "affiliations": ["maven", "dpg"],
  "areas_working_on": ["none", "should exist"],
  "birthdate": "1975-01-01"
}

###
GET http://127.0.0.1:8000/api/v1/users/public/get_all_coaches

###
GET http://sick-bjj-app.onrender.com/api/v1/users/authorised/get_all_coaches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiYWNoYWwyQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6IjU1Y2IwNWY4LWY2OWItNGE3Yi1hMzJjLTkxNjJkZjVjOGFlNyIsInJvbGUiOiJDb2FjaCJ9LCJleHAiOjE3NDI5MjIxOTcsImp0aSI6IjkyOWExMTAyLTNhNDMtNGFlYy05NzU3LTdkY2NiMzk0MzVlMyIsInJlZnJlc2giOmZhbHNlfQ.w93sy_LMOGpVgF4itjQMBu8hcdJng0uNpzkdwxxI32I


###
GET http://sick-bjj-app.onrender.com/api/v1/users/authorised/coach/AnaCarolina_1981
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiYWRhbWhpZ2h0b3dlcmVsbGlzQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6ImI0ODIxNDFlLWFjZTUtNGI3OS05OTY5LTMzMzRmZDllMmI0OCIsInJvbGUiOiJTdHVkZW50In0sImV4cCI6MTc0MzAwODM1NCwianRpIjoiODNhMWYwZGMtNDI3YS00NmM3LTgwYTQtZDkwYmM5YjY1OWUzIiwicmVmcmVzaCI6ZmFsc2V9.ccBT6NDegTrnC6lZ_cb5V6yw_9FxCJAGu9Eto3RGfb4

###
GET http://sick-bjj-app.onrender.com/api/v1/users/public/coach/AnaCarolina_1981

###
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "student1@example.com",
  "password": "securepassword"
}

###
GET http://127.0.0.1:8000/api/v1/users/my_profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoic3R1ZGVudDFAZXhhbXBsZS5jb20iLCJ1c2VyX2lkIjoiMGYxMjMyYTMtMmIxMS00M2JiLWI1ZjAtOWFhN2JhOTgxZmRlIiwicm9sZSI6IlN0dWRlbnQifSwiZXhwIjoxNzQzMTY0NTAwLCJqdGkiOiIwYmVkYWU2OC1jYzY0LTQ5Y2MtODY0NS0xMDE3MDcxMTZiZDIiLCJyZWZyZXNoIjpmYWxzZX0.4UtMJyahQL0vZxegGxzOqVRUuZpvzeuWLPfciZ5gwNw


###
POST http://127.0.0.1:8000/api/v1/sessions/create_feedback_session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoic3R1ZGVudDFAZXhhbXBsZS5jb20iLCJ1c2VyX2lkIjoiMGYxMjMyYTMtMmIxMS00M2JiLWI1ZjAtOWFhN2JhOTgxZmRlIiwicm9sZSI6IlN0dWRlbnQifSwiZXhwIjoxNzQzMTA0OTkxLCJqdGkiOiI4MjNmZjY2Ny1hNjcxLTRhOTItOGY1ZS1lNzc1ZjdjNzFkZDMiLCJyZWZyZXNoIjpmYWxzZX0.2KW98fSa2VTN8xYsS-3-cwQZj9Cm4EigDCVZN_TFyKA

{
  "title": "I am a spaz please help me bro",
  "video": "https://example.com/video.mp4",
  "message": "Help me i suck at BJJ!",
  "coach_username": "Coach1"
}