POST http://127.0.0.1:8000/api/v1/users/create_user
Content-Type: application/json


{
  "email": "123@example.com",
  "password": "securepassword",
  "role": "Coach",
  "username": "123",
  "belt": "Brown"
}

###
GET http://127.0.0.1:8000/api/v1/users/public/get_all_coaches

###
GET http://127.0.0.1:8000/api/v1/users/authorised/get_all_coaches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiYWNoYWwyQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6IjU1Y2IwNWY4LWY2OWItNGE3Yi1hMzJjLTkxNjJkZjVjOGFlNyIsInJvbGUiOiJDb2FjaCJ9LCJleHAiOjE3NDI5MjIxOTcsImp0aSI6IjkyOWExMTAyLTNhNDMtNGFlYy05NzU3LTdkY2NiMzk0MzVlMyIsInJlZnJlc2giOmZhbHNlfQ.w93sy_LMOGpVgF4itjQMBu8hcdJng0uNpzkdwxxI32I


###
GET http://127.0.0.1:8000/api/v1/users/authorised/coach/AdamHightowerEllis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiYWNoYWwyQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6IjU1Y2IwNWY4LWY2OWItNGE3Yi1hMzJjLTkxNjJkZjVjOGFlNyIsInJvbGUiOiJDb2FjaCJ9LCJleHAiOjE3NDI5MjIxOTcsImp0aSI6IjkyOWExMTAyLTNhNDMtNGFlYy05NzU3LTdkY2NiMzk0MzVlMyIsInJlZnJlc2giOmZhbHNlfQ.w93sy_LMOGpVgF4itjQMBu8hcdJng0uNpzkdwxxI32I

###
GET http://127.0.0.1:8000/api/v1/users/public/coach/AdamHightowerEllis

###
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "xanderibeiro@example.com",
  "password": "securepassword"
}

###
GET http://127.0.0.1:8000/api/v1/users/my_profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoieGFuZGVyaWJlaXJvQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6IjM1Yzg4OWI3LTQ0OTgtNDliZS04YjExLTI4ZDQwMjFiYWUxZiIsInJvbGUiOiJCb3RoIn0sImV4cCI6MTc0Mjk4NTk5MywianRpIjoiOWUxY2IwZjUtZjJkMi00YzgxLTg1OGItNzUwMjE0OWNiNDNmIiwicmVmcmVzaCI6ZmFsc2V9.X1625hEI1nyCn7dKgtqcan5qke6Wfm2AAgdvLRTrD7k
