"""t

Revision ID: 6d114ffc6f79
Revises: 4246f83c704b
Create Date: 2025-03-19 11:52:01.437319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d114ffc6f79'
down_revision: Union[str, None] = '4246f83c704b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_users', 'role',
               existing_type=postgresql.ENUM('Student', 'Coach', 'Both', name='role'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_users', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('Student', 'Coach', 'Both', name='role'),
               existing_nullable=False)
    # ### end Alembic commands ###
