"""init

Revision ID: 89b4c307b047
Revises: 
Create Date: 2025-03-14 11:38:58.677760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89b4c307b047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DimGym',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('gym_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('gym_id')
    )
    op.create_table('fact_user',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('belt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_ruleset', sa.String(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_links', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('competition_history', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('associations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('birthdate', sa.Integer(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_deactivated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('fact_coach',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('expertise', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('affiliations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('coach_bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('reviews_given', sa.Integer(), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['fact_user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id')
    )
    op.create_table('fact_student',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('areas_working_on', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_coach_style', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['fact_user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_student')
    op.drop_table('fact_coach')
    op.drop_table('fact_user')
    op.drop_table('DimGym')
    # ### end Alembic commands ###
