"""update password field

Revision ID: 9a48f8ec105c
Revises: 89b4c307b047
Create Date: 2025-03-14 12:17:54.262939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a48f8ec105c'
down_revision: Union[str, None] = '89b4c307b047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('fact_user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('fact_user', 'password_hash')
    # ### end Alembic commands ###
