"""add price to coach

Revision ID: bd0fdb587044
Revises: a088c4b8135f
Create Date: 2025-03-25 09:57:34.078632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd0fdb587044'
down_revision: Union[str, None] = 'a088c4b8135f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_coaches', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_coaches', 'price')
    # ### end Alembic commands ###
