"""feedback tables

Revision ID: bee982b357dc
Revises: 
Create Date: 2025-03-26 17:10:57.109292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bee982b357dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_feedbacksessions',
    sa.Column('feedback_session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status', sa.Enum('AWAITING_FEEDBACK', 'FEEDBACK_GIVEN', name='feedbackstatus'), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_by_coach', sa.Boolean(), nullable=False),
    sa.Column('closed_by_student', sa.Boolean(), nullable=False),
    sa.Column('review_by_student', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('review_by_coach', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['dim_coaches.coach_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['dim_students.student_id'], ),
    sa.PrimaryKeyConstraint('feedback_session_id')
    )
    op.create_table('fact_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('feedback_session_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'AUDIO', 'VIDEO', name='messagetype'), nullable=False),
    sa.Column('message_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_session_id'], ['fact_feedbacksessions.feedback_session_id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['dim_users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_messages')
    op.drop_table('fact_feedbacksessions')
    # ### end Alembic commands ###
